Adjust the init.d script and enhance it to leave the result of the ossec-control script in a log file

diff --git a/debian/ossec-hids-server.init b/debian/ossec-hids-server.init
--- a/debian/ossec-hids-server.init
+++ b/debian/ossec-hids-server.init
@@ -1,8 +1,7 @@
 #!/bin/sh
-# OSSEC	        Controls OSSEC HIDS
-# Author:       Daniel B. Cid <dcid@ossec.net>
-# Modified for slackware by Jack S. Lai
-# Modified for Debian by Javier Fernandez-Sanguino
+#
+# Debian init.d file for OSSEC HIDS (server)
+# Created for Debian by Javier Fernandez-Sanguino <jfs@debian.org>
 #
 # OSSEC HIDS is a free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License (version 2) as
@@ -23,41 +22,85 @@
 #                    active response. 
 ### END INIT INFO
 
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="OSSEC Host-based Intrusion Detection System"
+NAME=ossec-hids-server
+DAEMON=/usr/lib/ossec/ossec-agentd
+DAEMON_ARGS=""
+PIDFILE=/var/run/ossec-hids/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
 
-test $DEBIAN_SCRIPT_DEBUG && set -v -x
+# Exit if the package is not installed
+[ -x $DAEMON ] || exit 0
 
-DAEMON=ossec-hids
-NAME=ossec
-DESC="Host-based Intrusion Detection System"
-
-. /lib/lsb/init-functions
-
+# Load the information for the main configuration file
 [ -e /etc/ossec-init.conf ] && . /etc/ossec-init.conf
-if [ "X${DIRECTORY}" = "X" ]; then
+if [ -z "${DIRECTORY}" ]; then
     DIRECTORY="/var/ossec"
 fi
 
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+test $DEBIAN_SCRIPT_DEBUG && set -v -x
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
+. /lib/lsb/init-functions
+
 # If we don't find DIRECTORY then exit without error, the
-# package is not installed
+# package is not properly installed
 [ ! -e "${DIRECTORY}" ] && exit 0
 
-    
-start() {
-       [ -n "$DEBIAN_SCRIPT_DEBUG" ] && OUT=">/dev/null"
-	${DIRECTORY}/bin/ossec-control start $OUT
-       return $?
+# Create the directory for the pidfiles
+[ ! -e /var/run/ossec-hids ] && mkdir -p /var/run/ossec-hids
+
+# Log file for the ossec-control file
+LOGDIR=${DIRECTORY}/logs
+LOGFILE=${LOGDIR}/ossec-control.log
+
+# Function that tests the rules
+do_test_rules()
+{
+	echo | ${DIRECTORY}/ossec-logtest > /dev/null 2>&1;
+	if [ ! $? = 0 ]; then
+		log_failure_msg "the OSSEC ruleset is not valid, the daemon will not start. Review the output of ${DIRECTORY}/ossec-logtest"
+		return 1
+	fi
+	return 0
 }
 
-stop() {
-       [ -n "$DEBIAN_SCRIPT_DEBUG" ] && OUT=">/dev/null"
-	${DIRECTORY}/bin/ossec-control stop
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+       [ -n "$DEBIAN_SCRIPT_DEBUG" ] && OUT=">$LOGFILE 2>&1"
+       ${DIRECTORY}/bin/ossec-control start $OUT 
        return $?
+       # TODO REVIEW - Return
+       #   0 if daemon has been started
+       #   1 if daemon was already running
+       #   2 if daemon could not be started
 }
 
-status() {
-       [ -n "$DEBIAN_SCRIPT_DEBUG" ] && OUT=">/dev/null"
-	${DIRECTORY}/bin/ossec-control status
+do_stop() {
+       [ -n "$DEBIAN_SCRIPT_DEBUG" ] && OUT=">$LOGFILE 2>&1"
+       ${DIRECTORY}/bin/ossec-control stop $OUT
+       return $?
+       # TODO REVIEW - Return
+       #   0 if daemon has been stopped
+       #   1 if daemon was already stopped
+       #   2 if daemon could not be stopped
+       #   other if a failure occurred
+}
+
+do_status() {
+       [ -n "$DEBIAN_SCRIPT_DEBUG" ] && OUT=">$LOGFILE 2>&1"
+       ${DIRECTORY}/bin/ossec-control status $OUT
        return $?
 }
 
@@ -65,37 +108,54 @@ status() {
 case "$1" in
   start)
         log_daemon_msg "Starting $DESC " "$NAME"
-	start
+	do_start
         myret=$?
         if  [ $myret -eq 0 ] ; then
             log_end_msg 0
         else
+	    log_failure_msg "review the logfile $LOGFILE"
             log_end_msg 1
         fi
         exit $myret
 	;;
   stop) 
         log_daemon_msg "Stopping $DESC " "$NAME"
-	stop
+	do_stop
         myret=$?
         if  [ $myret -eq 0 ] ; then
             log_end_msg 0
         else
+	    log_failure_msg "review the logfile $LOGFILE"
             log_end_msg 1
         fi
         exit $myret
 	;;
   restart|force-restart|reload|force-reload)
-        $0 stop
-	$0 start
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+	  	# Failed to stop
+		log_end_msg 1
+		;;
+	esac
 	;;
   status)
         log_daemon_msg "Status of $NAME"
-        status
+	do_status
         myret=$?
         if  [ $myret -eq 0 ] ; then
             log_end_msg 0
         else
+	    log_failure_msg "review the logfile $LOGFILE"
             log_end_msg 1
         fi
         exit $myret
@@ -106,3 +166,5 @@ case "$1" in
 esac
 
 exit 0
+
+
